version: "2.0"
services:

  # PHP Application
  app:
    build: .
    links:
      - database
    encrypted_env_file: .env.encrypted
    command: cron -f

  # Database
  database:
    image: mariadb
    encrypted_env_file: .env.encrypted

  # Composer
  composer:
    image: composer/composer
    volumes:
      - ./:/app

  # Deployer
  deployer:
    build: ./deployer
    encrypted_env_file: deployer/.env.encrypted
